---
title: "Introduction to HW 3 Vig"
author: "Sidonia Zinky"
date: "2018 March"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{"Introduction to HW 3 Vig"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Function 1
Purpose: to compute mean, (population) varience, and (population) SD 
Details: takes in a vector x, returns a list with all those components.
Equations used ...
mean:
$$\mu = \sum_{i=1}^n p_i x_i$$
pop var:
$$\sigma^2 = \sum_{i=1}^n (x_i-\mu)^2 p_i$$
SD is square root of the var
``` {r}
x<-rnorm(10)
func1 <- function(x){
  a = sum(x)/length(x)
  b = sum((x-a)^2)/length(x)
  c = sqrt(b)
  return(list(mean=a,var=b,sd=c))
}
func1(x)
```

## Function 2
Same as above but with user checks for non-numeric, infinte, NA, NaN values
``` {r}
x<-rnorm(10)
func2 <- function(x){
  stopifnot(is.numeric(x))
  stopifnot(length(x)!=0)
  stopifnot(is.finite(x))
  stopifnot(!is.na(x))
  stopifnot(!is.nan(x))

  a = sum(x)/length(x)
  b = sum((x-a)^2)/length(x)
  c = sqrt(b)
  return(list(mean=a,var=b,sd=c))
}
func2(x)
```

